cat_media_upload_file:
    path:     /upload
    defaults: { _controller: CatalystMediaBundle:Upload:upload }


cat_media_upload_doc:
    path:     /upload_doc
    defaults: { _controller: CatalystMediaBundle:Upload:uploadDoc }
