acl:
    - category: Inventory
      entries:
        - id: cat_inv.menu
          label: "Menu"
#    - category: Warehouse
#      entries:
#        - id: cat_inv_wh.menu
#          label: "Menu"
#        - id: cat_inv_wh.view
#          label: "View"
#        - id: cat_inv_wh.add
#          label: "Add"
#        - id: cat_inv_wh.edit
#          label: "Edit"
#        - id: cat_inv_wh.delete
#          label: "Delete"
    - category: Stock Transfer
      entries:
        - id: gist_inv_stock_transfer.menu
          label: "Menu"
        - id: gist_inv_stock_transfer.view
          label: "View"
        - id: gist_inv_stock_transfer.add
          label: "Add"
        - id: gist_inv_stock_transfer.edit
          label: "Edit"
        - id: gist_inv_stock_transfer.delete
          label: "Delete"
    - category: Damaged Items
      entries:
        - id: gist_inv_damaged_items.menu
          label: "Menu"
        - id: gist_inv_damaged_items.view
          label: "View"
        - id: gist_inv_damaged_items.add
          label: "Add"
        - id: gist_inv_damaged_items.edit
          label: "Edit"
        - id: gist_inv_damaged_items.delete
          label: "Delete"
    - category: Inventory Locations
      entries:
        - id: gist_inv_loc.menu
          label: "Menu"
        - id: gist_inv_loc.view
          label: "View"
        - id: gist_inv_loc.add
          label: "Add"
        - id: gist_inv_loc.edit
          label: "Edit"
        - id: gist_inv_loc.delete
          label: "Delete"
    - category: Brand
      entries:
        - id: cat_inv_brand.menu
          label: "Menu"
        - id: cat_inv_brand.view
          label: "View"
        - id: cat_inv_brand.add
          label: "Add"
        - id: cat_inv_brand.edit
          label: "Edit"
        - id: cat_inv_brand.delete
          label: "Delete"
    - category: Product Category
      entries:
        - id: cat_inv_product_category.menu
          label: "Menu"
        - id: cat_inv_product_category.view
          label: "View"
        - id: cat_inv_product_category.add
          label: "Add"
        - id: cat_inv_product_category.edit
          label: "Edit"
        - id: cat_inv_product_category.delete
          label: "Delete"
    - category: Product Type
      entries:
        - id: cat_inv_product_type.menu
          label: "Menu"
        - id: cat_inv_product_type.view
          label: "View"
        - id: cat_inv_product_type.add
          label: "Add"
        - id: cat_inv_product_type.edit
          label: "Edit"
        - id: cat_inv_product_type.delete
          label: "Delete"
    - category: Product Group
      entries:
        - id: cat_inv_pg.menu
          label: "Menu"
        - id: cat_inv_pg.view
          label: "View"
        - id: cat_inv_pg.add
          label: "Add"
        - id: cat_inv_pg.edit
          label: "Edit"
        - id: cat_inv_pg.delete
          label: "Delete"
    - category: Product
      entries:
        - id: cat_inv_prod.menu
          label: "Menu"
        - id: cat_inv_prod.view
          label: "View"
        - id: cat_inv_prod.add
          label: "Add"
        - id: cat_inv_prod.edit
          label: "Edit"
        - id: cat_inv_prod.delete
          label: "Delete"
        - id: cat_inv_prod.price_change
          label: "Grid Price Change"
        - id: cat_inv_prod.view_sell_price
          label: "View Sell Price"
        - id: cat_inv_prod.view_cost_price
          label: "View Cost Price"
        - id: cat_inv_prod.restricted
          label: "Restricted Product"
    - category: Service Task
      entries:
        - id: cat_inv_sv_task.menu
          label: "Menu"
        - id: cat_inv_sv_task.view
          label: "View"
    - category: Transaction
      entries:
        - id: cat_inv_trans.menu
          label: "Menu"
    - category: Supplier
      entries:
        - id: gist_supplier.menu
          label: "Parent Menu"
        - id: gist_supp.menu
          label: "Menu"
        - id: gist_supp.view
          label: "View"
        - id: gist_supp.add
          label: "Add"
        - id: gist_supp.edit
          label: "Edit"
        - id: gist_supp.delete
          label: "Delete"
    - category: Point of Sales (POS)
      entries:
        - id: gist_inv_pos.menu
          label: "Menu"
        - id: gist_inv_pos.view
          label: "View"
        - id: gist_inv_pos.add
          label: "Add"
        - id: gist_inv_pos.edit
          label: "Edit"
        - id: gist_inv_pos.delete
          label: "Delete"
    - category: Stock Adjustment
      entries:
        - id: cat_inv_adjust.menu
          label: "Menu"
        - id: cat_inv_adjust.view
          label: "View"
        - id: cat_inv_adjust.add
          label: "Add"
        - id: cat_inv_adjust.edit
          label: "Edit"
        - id: cat_inv_adjust.delete
          label: "Delete"
    - category: Existing Stock
      entries:
        - id: gist_inv_existing_stock.menu
          label: "Menu"
        - id: gist_inv_existing_stock.view
          label: "View"
        - id: gist_inv_existing_stock.add
          label: "Add"
        - id: gist_inv_existing_stock.edit
          label: "Edit"
        - id: gist_inv_existing_stock.delete
          label: "Delete"
    - category: Damaged Item Reasons
      entries:
        - id: gist_inv_damaged_item_reason.menu
          label: "Menu"
        - id: gist_inv_damaged_item_reason.view
          label: "View"
        - id: gist_inv_damaged_item_reason.add
          label: "Add"
        - id: gist_inv_damaged_item_reason.edit
          label: "Edit"
        - id: gist_inv_damaged_item_reason.delete
          label: "Delete"
    - category: Existing Stock
      entries:
        - id: gist_inv_counting.menu
          label: "Menu"
        - id: gist_inv_counting.view
          label: "View"
        - id: gist_inv_counting.add
          label: "Add"
        - id: gist_inv_counting.edit
          label: "Edit"
        - id: gist_inv_counting.delete
          label: "Delete"