config:
    - category: "Inventory Settings"
      entries:
#        - id: gist_main_warehouse
#          label: "Main Warehouse"
#          type: select
#          options_service: gist_inventory
#          options_method: getWarehouseOptions
#        - id: gist_damaged_items_warehouse
#          label: "Damaged Items Warehouse"
#          type: select
#          options_service: gist_inventory
#          options_method: getWarehouseOptions
#        - id: gist_stock_threshold_formula_span
#          label: "Stock Formula Span"
#          type: select
#          options_service: gist_inventory
#          options_method: getFormulaSpanOptions
#        - id: gist_fixed_asset_brand
#          label: "Fixed Assets Brand"
#          type: select
#          options_service: gist_inventory
#          options_method: getBrandsOptions
        - id: gist_pos_counting_system_count_visibility
          label: "POS Counting Rule"
          type: select
          options_service: gist_inventory
          options_method: getCountingFormControl
        - id: gist_pos_counting_max_submissions
          label: "Counting Max Submissions"
          type: number
        - id: gist_pos_max_refund_days
          label: "POS Max Refund Day/s"
          type: number
        - id: gist_pos_refund_code
          label: "POS Refund Code"
          type: text
        - id: gist_pos_upsell_seconds
          label: "POS Upsell Time (seconds)"
          type: number