config:
    - category: "Inventory Settings"
      entries:
        - id: gist_main_warehouse
          label: "Main Warehouse"
          type: select
          options_service: gist_inventory
          options_method: getWarehouseOptions
        - id: gist_adjustment_warehouse
          label: "Adjustment Warehouse"
          type: select
          options_service: gist_inventory
          options_method: getWarehouseOptions
