menu_items:
    - id: menu_inventory
      acl: cat_inv.menu
      label: Inventory
      icon: fa-dropbox
    - id: cat_inv_prod_index
      acl: cat_inv_prod.menu
      label: Products
      parent: menu_inventory
    - id: cat_inv_brand_index
      acl: cat_inv_brand.menu
      label: Brand
      parent: menu_inventory
    - id: cat_inv_product_category_index
      acl: cat_inv_product_category.menu
      label: Category
      parent: menu_inventory
    - id: cat_inv_product_type_index
      acl: cat_inv_product_type.menu
      label: Product Type
      parent: menu_inventory
    - id: gist_inv_existing_stock_index
      acl: gist_inv_existing_stock.menu
      label: Existing Stock
      parent: menu_inventory
#    - id: gist_inv_existing_stock_by_product_index
#      acl: gist_inv_existing_stock_by_product.menu
#      label: Existing Stock (Product)
#      parent: menu_inventory
    - id: gist_inv_counting_index
      acl: gist_inv_counting.menu
      label: Counting Submissions
      parent: menu_inventory
    - id: gist_inv_counting_gridform_index
      acl: gist_inv_counting_gridform.menu
      label: Counting Form
      parent: menu_inventory
    - id: gist_inv_stock_transfer_index
      acl: gist_inv_stock_transfer.menu
      label: Stock Transfer
      parent: menu_inventory
    - id: gist_inv_damaged_items_index
      acl: gist_inv_damaged_items.menu
      label: Damaged Items
      parent: menu_inventory
    - id: gist_inv_damaged_item_reason_index
      acl: gist_inv_damaged_item_reason.menu
      label: Damaged Item Reason
      parent: menu_inventory
    - id: gist_inv_loc_index
      acl: gist_inv_loc.menu
      label: Location
      parent: menu_inventory
    - id: cat_inv_adjust_index
      acl: cat_inv_adjust.menu
      label: Stock Adjustment
      parent: menu_inventory
    - id: gist_supp_index
      acl: gist_supp.menu
      label: Supplier
      parent: menu_inventory
    - id: gist_inv_settings_index
      acl: gist_inv_settings.menu
      label: Inventory Settings
      parent: menu_inventory
