#parameters:
#    gist_inventory.example.class: Gist\InventoryBundle\Example

services:
    gist_inventory:
        class: Gist\InventoryBundle\Model\InventoryManager
        arguments:
            em: "@doctrine.orm.entity_manager"
            container: "@service_container"
            security: "@security.context"
    gist_inventory_stock_transfer:
            class: Gist\InventoryBundle\Model\InventoryStockTransferManager
            arguments:
                em: "@doctrine.orm.entity_manager"
                container: "@service_container"
                security: "@security.context"

    gist_inventory_damaged_items_managed:
              class: Gist\InventoryBundle\Model\InventoryDamagedItemsManager
              arguments:
                  em: "@doctrine.orm.entity_manager"
                  container: "@service_container"
                  security: "@security.context"

    gist_inventory_product_manager:
              class: Gist\InventoryBundle\Model\InventoryProductManager
              arguments:
                  em: "@doctrine.orm.entity_manager"
                  container: "@service_container"
                  security: "@security.context"

    gist_options_manager:
              class: Gist\InventoryBundle\Model\OptionsManager
              arguments:
                  em: "@doctrine.orm.entity_manager"
                  container: "@service_container"
                  security: "@security.context"

    gist_stock_manipulation_manager:
              class: Gist\InventoryBundle\Model\StockManipulationManager
              arguments:
                  em: "@doctrine.orm.entity_manager"
                  container: "@service_container"
                  security: "@security.context"
    gist_layered_report_service:
              class: Gist\SalesReportBundle\Model\LayeredReportDataManager
              arguments:
                  em: "@doctrine.orm.entity_manager"
                  container: "@service_container"
                  security: "@security.context"
