menu_items:
    - id: menu_customer
      acl: gist_customer.menu
      label: CRM
      icon: fa-user
    - id: gist_customer_list_index
      acl: gist_customer_list.menu
      label: Customers
      parent: menu_customer
    - id: gist_customer_fields_index
      acl: gist_customer_fields.menu
      label: POS Form Fields
      parent: menu_customer

