# gist_customer_index:
#     path:     /list
#     defaults: { _controller: GistCustomerBundle:List:index }


#LIST
gist_customer_list_index:
    pattern: /customer_list
    methods: [GET]
    defaults: { _controller: GistCustomerBundle:Customer:index }

gist_customer_list_add_form:
    pattern: /customer
    methods: [GET]
    defaults: { _controller: GistCustomerBundle:Customer:addForm }

gist_customer_list_add_submit:
    pattern: /customer
    methods: [POST]
    defaults: { _controller: GistCustomerBundle:Customer:addSubmit }

gist_customer_list_edit_form:
    pattern: /customer/{id}
    methods: [GET]
    defaults: { _controller: GistCustomerBundle:Customer:editForm }

gist_customer_list_edit_submit:
    pattern: /customer/{id}
    methods: [POST]
    defaults: { _controller: GistCustomerBundle:Customer:editSubmit }

gist_customer_list_delete:
    pattern: /customer/{id}/delete
    methods: [GET]
    defaults: { _controller: GistCustomerBundle:Customer:delete }

gist_customer_list_grid:
    pattern: /customer_list/grid
    methods: [GET]
    defaults: { _controller: GistCustomerBundle:Customer:grid }

gist_customer_list_logs:
    pattern: /customer_list/logs/{id}
    methods: [GET]
    defaults: { _controller: GistCustomerBundle:Customer:viewLogs }

gist_customer_pos_search:
    pattern: /pos/search/{first_name}/{last_name}/{email}/{number}/{mname}/{id}/{gender}/{marital_status}/{date_married}/{home_phone}/{birthdate}/{add1}/{add2}/{city}/{state}/{country}/{zip}
    methods: [GET]
    defaults: { _controller: GistCustomerBundle:Customer:searchCustomer }

gist_customer_pos_add:
    pattern: /pos/add/{first_name}/{last_name}/{email}/{number}/{mname}/{gender}/{marital_status}/{date_married}/{home_phone}/{birthdate}/{add1}/{add2}/{city}/{state}/{country}/{zip}/{notes}
    methods: [GET]
    defaults: { _controller: GistCustomerBundle:Customer:addCustomer }

#FIELDS
gist_customer_fields_index:
    pattern: /fields
    methods: [GET]
    defaults: { _controller: GistCustomerBundle:Fields:index }

# gist_customer_fields_add_form:
#     pattern: /field
#     methods: [GET]
#     defaults: { _controller: GistCustomerBundle:Fields:addForm }

gist_customer_fields_add_submit:
    pattern: /fields
    methods: [POST]
    defaults: { _controller: GistCustomerBundle:Fields:editSubmit2 }

gist_customer_fields_get:
    pattern: /fields/get_req    
    methods: [GET]
    defaults: { _controller: GistCustomerBundle:Fields:getRequiredFields }

# gist_customer_fields_edit_form:
#     pattern: /field/{id}
#     methods: [GET]
#     defaults: { _controller: GistCustomerBundle:Fields:editForm }

# gist_customer_fields_edit_submit:
#     pattern: /field/{id}
#     methods: [POST]
#     defaults: { _controller: GistCustomerBundle:Fields:editSubmit }



