gist_accounting_pl_index:
    pattern: /list
    methods: [GET]
    defaults: { _controller: GistAccountingBundle:ProfitAndLoss:index }

gist_accounting_pl_generate:
    pattern: /list
    methods: [POST]
    defaults: { _controller: GistAccountingBundle:ProfitAndLoss:generateCSV }

gist_accounting_pl_generate_table:
    pattern: /list_table/{from}/{to}
    methods: [GET]
    defaults: { _controller: GistAccountingBundle:ProfitAndLoss:generateTable }

gist_pnl_settings_index:
    pattern: /list_settings
    methods: [GET]
    defaults: { _controller: GistAccountingBundle:ProfitAndLossSettings:index }

gist_pnl_settings_generate:
    pattern: /list_settings
    methods: [POST]
    defaults: { _controller: GistAccountingBundle:ProfitAndLossSettings:save }