parameters:
#    hris_employee_satisfaction.example.class: Hris\EmployeeSatisfactionBundle\Example

services:
#    hris_employee_satisfaction.example:
#        class: %hris_employee_satisfaction.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
