security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            form_login:
                check_path: /login_check
                login_path: /login
                provider: fos_userbundle
                default_target_path: /
                always_use_default_target_path: true
            logout:
                path: /logout
                target: /
            anonymous: ~
            switch_user: { role: ROLE_ADMIN, parameter: _switch }


    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inventory/pos/get/product_categories$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inventory/pos/get/products, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inventory/pos/get/vat, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inventory/pos/get/deposit_minimum, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inventory/pos/get/banks, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inventory/pos/get/terminal_operators, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inventory/pos/get/tax_coverage, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inventory/pos/get/upsell_time, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inventory/pos/get/exchange_rule_below, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/customer/pos/search, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/customer/pos/add, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/pos_erp/get/charge_rates, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/pos_erp/save_transaction, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/pos_erp/save_item, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/pos_erp/save_payment, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/customer/fields/get_req, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/customer/get/all, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/pos_erp/get/users, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/pos_erp/get/products, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/inventory/stock_transfer/get/from, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inventory/stock_transfer/get/to, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inventory/stock_transfer/get/data, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inventory/stock_transfer/get/data_rollback, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inventory/stock_transfer/get/data_entries, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inventory/stock_transfer/get/loc_options, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inventory/stock_transfer/update_status, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inventory/stock_transfer/add_new, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inventory/damaged_items/get/prod_cats, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/inventory/damaged_items/search_product/ajax, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inventory/damaged_items/search_product/ajax2, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inventory/damaged_items/entry/status, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inventory/damaged_items/get/damaged_stocks, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inventory/damaged_items/get/from, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inventory/damaged_items/get/to, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inventory/damaged_items/get/data, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inventory/damaged_items/get/data_entries, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inventory/damaged_items/add_new, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inventory/damaged_items/pos/add_entries2, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/inventory/damaged_items/pos/get_receive_form_data, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inventory/damaged_items/pos/get_receive_form_data_entries, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inventory/damaged_items/pos/receive_items, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inventory/damaged_items/pos/summary_table, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/inventory/damaged_items/pos/get_selected_for_return, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inventory/damaged_items/pos/save_for_return, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/inventory/damaged_items/pos/update_rollback, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/inventory/damaged_items/get/prod_cats, roles: IS_AUTHENTICATED_ANONYMOUSLY }
#        - { path: ^/inventory/damaged_items/get/prod_cats, roles: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/customer/fields/get_visible, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
