parameters:
#    hris_company_overview.example.class: Hris\CompanyOverviewBundle\Example

services:
#    hris_company_overview.example:
#        class: %hris_company_overview.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
