acl:
    - category: Sales Report
      entries:
        - id: gist_sales_report.menu
          label: Menu
    - category: Main Sales Report
      entries:
        - id: gist_sales_report_main.menu
          label: Menu
        - id: gist_sales_report_main.view
          label: View
    - category: Layered Sales Report
      entries:
        - id: gist_layered_sales_report.menu
          label: Menu
    - category: Product Layered Report
      entries:
        - id: gist_layered_sales_report_product.menu
          label: Menu
        - id: gist_layered_sales_report_product.view
          label: View
    - category: Location Layered Report
      entries:
        - id: gist_layered_sales_report_location.menu
          label: Menu
        - id: gist_layered_sales_report_location.view
          label: View
    - category: Employee Layered Report
      entries:
        - id: gist_layered_sales_report_employee.menu
          label: Menu
        - id: gist_layered_sales_report_employee.view
          label: View
    - category: Supplier Layered Report
      entries:
        - id: gist_layered_sales_report_supplier.menu
          label: Menu
        - id: gist_layered_sales_report_supplier.view
          label: View
    - category: Customer Layered Report
      entries:
        - id: gist_layered_sales_report_customer.menu
          label: Menu
        - id: gist_layered_sales_report_customer.view
          label: View
    - category: Sales Layered Report
      entries:
        - id: gist_layered_sales_report_sales.menu
          label: Menu
        - id: gist_layered_sales_report_sales.view
          label: View
#    - category: Sales Order Report
#      entries:
#        - id: gist_sales_report_sales_order.menu
#          label: Menu
#        - id: gist_sales_report_sales_order.view
#          label: View
#    - category: Sales Entries Report
#      entries:
#        - id: gist_sales_report_sales_entries.menu
#          label: Menu
#        - id: gist_sales_report_sales_entries.view
#          label: View
#    - category: Sales Per Day
#      entries:
#        - id: gist_sales_report_sales_per_day.menu
#          label: Menu
#        - id: gist_sales_report_sales_per_day.view
#          label: View
#    - category: Sales by Consultant
#      entries:
#        - id: gist_sales_report_sales_by_consultant.menu
#          label: Menu
#        - id: gist_sales_report_sales_by_consultant.view
#          label: View
#    - category: Sales by POS
#      entries:
#        - id: gist_sales_report_sales_by_pos.menu
#          label: Menu
#        - id: gist_sales_report_sales_by_pos.view
#          label: View
#    - category: Sales by Location
#      entries:
#        - id: gist_sales_report_sales_by_location.menu
#          label: Menu
#        - id: gist_sales_report_sales_by_location.view
#          label: View
#    - category: Sales by Product
#      entries:
#        - id: gist_sales_report_sales_by_product.menu
#          label: Menu
#        - id: gist_sales_report_sales_by_product.view
#          label: View
#    - category: Sales Commission
#      entries:
#        - id: gist_sales_report_sales_commission.menu
#          label: Menu
#        - id: gist_sales_report_sales_commission.view
#          label: View