acl:
    - category: Sales Report
      entries:
        - id: gist_sales_report.menu
          label: Menu
    - category: Sales Order Report
      entries:
        - id: gist_sales_report_sales_order.menu
          label: Menu
        - id: gist_sales_report_sales_order.view
          label: View
    - category: Sales Entries Report
      entries:
        - id: gist_sales_report_sales_entries.menu
          label: Menu
        - id: gist_sales_report_sales_entries.view
          label: View
    - category: Sales Per Day
      entries:
        - id: gist_sales_report_sales_per_day.menu
          label: Menu
        - id: gist_sales_report_sales_per_day.view
          label: View
    - category: Sales by Consultant
      entries:
        - id: gist_sales_report_sales_by_consultant.menu
          label: Menu
        - id: gist_sales_report_sales_by_consultant.view
          label: View
    - category: Sales by POS
      entries:
        - id: gist_sales_report_sales_by_pos.menu
          label: Menu
        - id: gist_sales_report_sales_by_pos.view
          label: View
    - category: Sales by Location
      entries:
        - id: gist_sales_report_sales_by_location.menu
          label: Menu
        - id: gist_sales_report_sales_by_location.view
          label: View
    - category: Sales by Product
      entries:
        - id: gist_sales_report_sales_by_product.menu
          label: Menu
        - id: gist_sales_report_sales_by_product.view
          label: View
    - category: Sales Commission
      entries:
        - id: gist_sales_report_sales_commission.menu
          label: Menu
        - id: gist_sales_report_sales_commission.view
          label: View