menu_items:
    - id: menu_sales_report
      acl: gist_sales_report.menu
      label: Sales Report
      icon: fa-file-o
    - id: gist_sales_report_main_summary
      acl: gist_sales_report_main.menu
      label: Main Report
      parent: menu_sales_report

    - id: menu_layered_sales_report
      acl: gist_layered_sales_report.menu
      label: Layered Sales Report
      icon: fa-archive
    - id: gist_layered_sales_report_product_index
      acl: gist_layered_sales_report_product.menu
      label: Product
      parent: menu_layered_sales_report
    - id: gist_layered_sales_report_location_index
      acl: gist_layered_sales_report_location.menu
      label: Location
      parent: menu_layered_sales_report
    - id: gist_layered_sales_report_employee_index
      acl: gist_layered_sales_report_employee.menu
      label: Employee
      parent: menu_layered_sales_report
#    - id: gist_sales_report_sales_order_summary
#      acl: gist_sales_report_sales_order.menu
#      label: Sales Orders
#      parent: menu_sales_report
#    - id: gist_sales_report_sales_entries_summary
#      acl: gist_sales_report_sales_entries.menu
#      label: Sales Entries
#      parent: menu_sales_report
#    - id: gist_sales_report_sales_per_day_summary
#      acl: gist_sales_report_sales_per_day.menu
#      label: Sales Per Day
#      parent: menu_sales_report
#    - id: gist_sales_report_sales_by_consultant_summary
#      acl: gist_sales_report_sales_by_consultant.menu
#      label: Sales by Consultant
#      parent: menu_sales_report
#    - id: gist_sales_report_sales_by_pos_summary
#      acl: gist_sales_report_sales_by_pos.menu
#      label: Sales by POS
#      parent: menu_sales_report
#    - id: gist_sales_report_sales_by_location_summary
#      acl: gist_sales_report_sales_by_location.menu
#      label: Sales by Location
#      parent: menu_sales_report
#    - id: gist_sales_report_sales_by_product_summary
#      acl: gist_sales_report_sales_by_product.menu
#      label: Sales by Product
#      parent: menu_sales_report
#    - id: gist_sales_report_sales_commission_summary
#      acl: gist_sales_report_sales_commission.menu
#      label: Sales Commission
#      parent: menu_sales_report