
gist_sales_report_main_summary:
    path: /main-report
    defaults: { _controller: GistSalesReportBundle:MainSalesReport:index }

gist_sales_report_main_ajax_grid:
    path:    /main_report/ajax/{id}/{date_from}/{date_to}/{type}/{mode}/{agent}/{customer}/{area}/{pos_loc}/{customer_id}
    defaults: { _controller: GistSalesReportBundle:MainSalesReport:gridReport,id: null, date_from: null, date_to: null, type: null, mode: null, agent: null, customer: null, area: null, pos_loc: null, customer_id: null }

gist_sales_report_main_ajax:
    path:    /main_report/{id}/{date_from}/{date_to}/{type}/{mode}/{agent}/{customer}/{area}/{pos_loc}/{customer_id}
    defaults: { _controller: GistSalesReportBundle:MainSalesReport:gridReport,id: null, date_from: null, date_to: null, type: null, mode: null, agent: null, customer: null, area: null, pos_loc: null, customer_id: null }

gist_sales_report_sales_order_summary:
    path: /sales-orders
    defaults: { _controller: GistSalesReportBundle:SalesOrderReport:index }


gist_sales_report_sales_entries_summary:
    path: /sales-entries
    defaults: { _controller: GistSalesReportBundle:SalesEntriesReport:index }


gist_sales_report_sales_per_day_summary:
    path: /sales-daily
    defaults: { _controller: GistSalesReportBundle:SalesPerDayReport:index }


gist_sales_report_sales_by_consultant_summary:
    path: /sales-consultant
    defaults: { _controller: GistSalesReportBundle:SalesByConsultantReport:index }

gist_sales_report_sales_by_pos_summary:
    path: /sales-pos
    defaults: { _controller: GistSalesReportBundle:SalesByPOSReport:index }

gist_sales_report_sales_by_location_summary:
    path: /sales-location
    defaults: { _controller: GistSalesReportBundle:SalesByLocationReport:index }

gist_sales_report_sales_by_product_summary:
    path: /sales-product
    defaults: { _controller: GistSalesReportBundle:SalesByProductReport:index }

gist_sales_report_sales_commission_summary:
    path: /sales-commission
    defaults: { _controller: GistSalesReportBundle:SalesCommissionReport:index }


#    LAYERED SALES REPORTS
#==========================================

# PRODUCTS
gist_layered_sales_report_product_index:
    path: /layered-sales-report/product/{date_from}/{date_to}/{brand}/{category}
    methods:  [GET]
    defaults: { _controller: GistSalesReportBundle:ProductLayeredReport:index, date_from: null, date_to: null, brand: null, category: null }

gist_layered_sales_report_product_index_filter:
    path: /layered-sales-report/product/{date_from}/{date_to}/{brand}/{category}
    methods:  [POST]
    defaults: { _controller: GistSalesReportBundle:ProductLayeredReport:index, date_from: null, date_to: null, brand: null, category: null }

gist_layered_sales_report_product_index_brands:
    path: /layered-sales-report/product_brands/{date_from}/{date_to}/{brand}/{category}
    methods:  [GET]
    defaults: { _controller: GistSalesReportBundle:ProductLayeredReport:brandsIndex, date_from: null, date_to: null, brand: null, category: null }

gist_layered_sales_report_product_index_branded:
    path: /layered-sales-report/product_branded/{date_from}/{date_to}/{brand}/{category}
    methods:  [GET]
    defaults: { _controller: GistSalesReportBundle:ProductLayeredReport:brandedIndex, date_from: null, date_to: null, brand: null, category: null }

gist_layered_sales_report_product_index_categorized:
    path: /layered-sales-report/product_categorized/{date_from}/{date_to}/{brand}/{category}
    methods:  [GET]
    defaults: { _controller: GistSalesReportBundle:ProductLayeredReport:categorizedIndex, date_from: null, date_to: null, brand: null, category: null }

# LOCATION
gist_layered_sales_report_location_index:
    path: /layered-sales-report/location/{date_from}/{date_to}
    methods:  [GET]
    defaults: { _controller: GistSalesReportBundle:LocationLayeredReport:index, date_from: null, date_to: null }

gist_layered_sales_report_location_index_filter:
    path: /layered-sales-report/location/{date_from}/{date_to}/{region}/{area}
    methods:  [POST]
    defaults: { _controller: GistSalesReportBundle:LocationLayeredReport:index, date_from: null, date_to: null, region: null, area: null }

gist_layered_sales_report_location_index_regions:
    path: /layered-sales-report/location_regions/{date_from}/{date_to}/{region}/{area}
    methods:  [GET]
    defaults: { _controller: GistSalesReportBundle:LocationLayeredReport:regionsIndex, date_from: null, date_to: null, region: null, area: null }

gist_layered_sales_report_location_index_areas:
    path: /layered-sales-report/location_areas/{date_from}/{date_to}/{region}/{area}
    methods:  [GET]
    defaults: { _controller: GistSalesReportBundle:LocationLayeredReport:areasIndex, date_from: null, date_to: null, region: null, area: null }

gist_layered_sales_report_location_index_locations:
    path: /layered-sales-report/location_pos/{date_from}/{date_to}/{region}/{area}
    methods:  [GET]
    defaults: { _controller: GistSalesReportBundle:LocationLayeredReport:posIndex, date_from: null, date_to: null, region: null, area: null }

# EMPLOYEE
gist_layered_sales_report_employee_index:
    path: /layered-sales-report/employee/{date_from}/{date_to}/{position}
    methods:  [GET]
    defaults: { _controller: GistSalesReportBundle:EmployeeLayeredReport:index, date_from: null, date_to: null, position: null }

gist_layered_sales_report_employee_index_filter:
    path: /layered-sales-report/employee/{date_from}/{date_to}/{position}
    methods:  [POST]
    defaults: { _controller: GistSalesReportBundle:EmployeeLayeredReport:index, date_from: null, date_to: null, position: null }

gist_layered_sales_report_employee_index_positions:
    path: /layered-sales-report/employee_positions/{date_from}/{date_to}/{position}
    methods:  [GET]
    defaults: { _controller: GistSalesReportBundle:EmployeeLayeredReport:positionsIndex, date_from: null, date_to: null, position: null }

gist_layered_sales_report_employee_index_employees:
    path: /layered-sales-report/employee_employees/{date_from}/{date_to}/{position}
    methods:  [GET]
    defaults: { _controller: GistSalesReportBundle:EmployeeLayeredReport:employeesIndex, date_from: null, date_to: null, position: null }

# SUPPLIER
gist_layered_sales_report_supplier_index:
    path: /layered-sales-report/supplier/{date_from}/{date_to}
    methods:  [GET]
    defaults: { _controller: GistSalesReportBundle:SupplierLayeredReport:index, date_from: null, date_to: null }

gist_layered_sales_report_supplier_index_filter:
    path: /layered-sales-report/supplier/{date_from}/{date_to}
    methods:  [POST]
    defaults: { _controller: GistSalesReportBundle:SupplierLayeredReport:index, date_from: null, date_to: null }

gist_layered_sales_report_supplier_index_list:
    path: /layered-sales-report/suppliers/{date_from}/{date_to}
    methods:  [GET]
    defaults: { _controller: GistSalesReportBundle:SupplierLayeredReport:suppliersIndex, date_from: null, date_to: null }

# CUSTOMER
gist_layered_sales_report_customer_index:
    path: /layered-sales-report/customer/{date_from}/{date_to}
    methods:  [GET]
    defaults: { _controller: GistSalesReportBundle:CustomerLayeredReport:index, date_from: null, date_to: null }

gist_layered_sales_report_customer_index_filter:
    path: /layered-sales-report/customer/{date_from}/{date_to}
    methods:  [POST]
    defaults: { _controller: GistSalesReportBundle:CustomerLayeredReport:index, date_from: null, date_to: null }

gist_layered_sales_report_customer_index_list:
    path: /layered-sales-report/customer_list/{date_from}/{date_to}
    methods:  [GET]
    defaults: { _controller: GistSalesReportBundle:CustomerLayeredReport:customersIndex, date_from: null, date_to: null }

gist_layered_sales_report_customer_index_transactions:
    path: /layered-sales-report/customer_transactions/{date_from}/{date_to}/{customer_id}
    methods:  [GET]
    defaults: { _controller: GistSalesReportBundle:CustomerLayeredReport:transactionsIndex, date_from: null, date_to: null, customer_id: null }

gist_layered_sales_report_customer_index_transaction_details:
    path: /layered-sales-report/customer_transaction/details/{date_from}/{date_to}/{id}/{customer_id}
    methods:  [GET]
    defaults: { _controller: GistSalesReportBundle:CustomerLayeredReport:viewTransactionDetails, date_from: null, date_to: null, id: null, customer_id: null }


# SALES
# L1
gist_layered_sales_report_sales_index:
    path: /layered-sales-report/sales/{date_from}/{date_to}
    methods:  [GET]
    defaults: { _controller: GistSalesReportBundle:SalesLayeredReport:index, date_from: null, date_to: null }

gist_layered_sales_report_sales_index_filter:
    path: /layered-sales-report/sales/{date_from}/{date_to}
    methods:  [POST]
    defaults: { _controller: GistSalesReportBundle:SalesLayeredReport:index, date_from: null, date_to: null }

# L2
gist_layered_sales_report_sales_index_modes:
    path: /layered-sales-report/sales_modes/{date_from}/{date_to}
    methods:  [GET]
    defaults: { _controller: GistSalesReportBundle:SalesLayeredReport:modesIndex, date_from: null, date_to: null }

# L3 - CASH
gist_layered_sales_report_sales_index_cash_transactions:
    path: /layered-sales-report/sales/cash_transactions/{date_from}/{date_to}/{mode}
    methods:  [GET]
    defaults: { _controller: GistSalesReportBundle:SalesLayeredReport:cashTransactionsIndex, date_from: null, date_to: null, mode: null }

# L3 - CARD - TERMINALS
gist_layered_sales_report_sales_index_card_terminals:
    path: /layered-sales-report/sales/card_terminals/{date_from}/{date_to}
    methods:  [GET]
    defaults: { _controller: GistSalesReportBundle:SalesLayeredReport:positionsIndex, date_from: null, date_to: null }

# L3 - CARD - TERMINALS
gist_layered_sales_report_sales_index_check_types:
    path: /layered-sales-report/sales/check_types/{date_from}/{date_to}
    methods:  [GET]
    defaults: { _controller: GistSalesReportBundle:SalesLayeredReport:positionsIndex, date_from: null, date_to: null }

# L4 - CARD - TRANSACTIONS
gist_layered_sales_report_sales_index_card_transactions:
    path: /layered-sales-report/sales/card_transactions/{date_from}/{date_to}/{terminal}
    methods:  [GET]
    defaults: { _controller: GistSalesReportBundle:SalesLayeredReport:positionsIndex, date_from: null, date_to: null, terminal: null }

# L4 - CHECK - TRANSACTIONS
gist_layered_sales_report_sales_index_check_transactions:
    path: /layered-sales-report/sales/check_transactions/{date_from}/{date_to}/{check_type}
    methods:  [GET]
    defaults: { _controller: GistSalesReportBundle:SalesLayeredReport:positionsIndex, date_from: null, date_to: null, check_type: null }