
gist_sales_report_main_summary:
    path: /main-report
    defaults: { _controller: GistSalesReportBundle:MainSalesReport:index }

gist_sales_report_main_ajax_grid:
    path:    /main_report/ajax/{id}/{date_from}/{date_to}/{type}/{mode}/{agent}/{customer}/{area}/{pos_loc}/{customer_id}
    defaults: { _controller: GistSalesReportBundle:MainSalesReport:gridReport,id: null, date_from: null, date_to: null, type: null, mode: null, agent: null, customer: null, area: null, pos_loc: null, customer_id: null }

gist_sales_report_main_ajax:
    path:    /main_report/{id}/{date_from}/{date_to}/{type}/{mode}/{agent}/{customer}/{area}/{pos_loc}/{customer_id}
    defaults: { _controller: GistSalesReportBundle:MainSalesReport:gridReport,id: null, date_from: null, date_to: null, type: null, mode: null, agent: null, customer: null, area: null, pos_loc: null, customer_id: null }

gist_sales_report_sales_order_summary:
    path: /sales-orders
    defaults: { _controller: GistSalesReportBundle:SalesOrderReport:index }


gist_sales_report_sales_entries_summary:
    path: /sales-entries
    defaults: { _controller: GistSalesReportBundle:SalesEntriesReport:index }


gist_sales_report_sales_per_day_summary:
    path: /sales-daily
    defaults: { _controller: GistSalesReportBundle:SalesPerDayReport:index }


gist_sales_report_sales_by_consultant_summary:
    path: /sales-consultant
    defaults: { _controller: GistSalesReportBundle:SalesByConsultantReport:index }

gist_sales_report_sales_by_pos_summary:
    path: /sales-pos
    defaults: { _controller: GistSalesReportBundle:SalesByPOSReport:index }

gist_sales_report_sales_by_location_summary:
    path: /sales-location
    defaults: { _controller: GistSalesReportBundle:SalesByLocationReport:index }

gist_sales_report_sales_by_product_summary:
    path: /sales-product
    defaults: { _controller: GistSalesReportBundle:SalesByProductReport:index }

gist_sales_report_sales_commission_summary:
    path: /sales-commission
    defaults: { _controller: GistSalesReportBundle:SalesCommissionReport:index }


#    LAYERED SALES REPORTS
#==========================================

# PRODUCTS
gist_layered_sales_report_product_index:
    path: /layered-sales-report/product/{date_from}/{date_to}/{brand}/{category}
    methods:  [GET]
    defaults: { _controller: GistSalesReportBundle:ProductLayeredReport:index, date_from: null, date_to: null, brand: null, category: null }

gist_layered_sales_report_product_index_filter:
    path: /layered-sales-report/product/{date_from}/{date_to}/{brand}/{category}
    methods:  [POST]
    defaults: { _controller: GistSalesReportBundle:ProductLayeredReport:index, date_from: null, date_to: null, brand: null, category: null }

gist_layered_sales_report_product_index_brands:
    path: /layered-sales-report/product_brands/{date_from}/{date_to}/{brand}/{category}
    methods:  [GET]
    defaults: { _controller: GistSalesReportBundle:ProductLayeredReport:brandsIndex, date_from: null, date_to: null, brand: null, category: null }

gist_layered_sales_report_product_index_branded:
    path: /layered-sales-report/product_branded/{date_from}/{date_to}/{brand}/{category}
    methods:  [GET]
    defaults: { _controller: GistSalesReportBundle:ProductLayeredReport:brandedIndex, date_from: null, date_to: null, brand: null, category: null }

gist_layered_sales_report_product_index_categorized:
    path: /layered-sales-report/product_categorized/{date_from}/{date_to}/{brand}/{category}
    methods:  [GET]
    defaults: { _controller: GistSalesReportBundle:ProductLayeredReport:categorizedIndex, date_from: null, date_to: null, brand: null, category: null }

# LOCATION
gist_layered_sales_report_location_index:
    path: /layered-sales-report/location/{date_from}/{date_to}
    methods:  [GET]
    defaults: { _controller: GistSalesReportBundle:LocationLayeredReport:index, date_from: null, date_to: null }

gist_layered_sales_report_location_index_filter:
    path: /layered-sales-report/location/{date_from}/{date_to}/{region}/{area}
    methods:  [POST]
    defaults: { _controller: GistSalesReportBundle:LocationLayeredReport:index, date_from: null, date_to: null, region: null, area: null }

gist_layered_sales_report_location_index_regions:
    path: /layered-sales-report/location_regions/{date_from}/{date_to}/{region}/{area}
    methods:  [GET]
    defaults: { _controller: GistSalesReportBundle:LocationLayeredReport:regionsIndex, date_from: null, date_to: null, region: null, area: null }

# EMPLOYEE
gist_layered_sales_report_employee_index:
    path: /layered-sales-report/employee
    methods:  [GET]
    defaults: { _controller: GistSalesReportBundle:EmployeeLayeredReport:index }