
gist_sales_report_main_summary:
    path: /main-report
    defaults: { _controller: GistSalesReportBundle:MainSalesReport:index }

gist_sales_report_main_ajax_grid:
    path:    /attendances/ajax/{id}/{department}/{date_from}/{date_to}/{position}/{rank}/{gender}/{days}/{late}/{late_to}/{undertime}/{undertime_to}/{status}/{location}
    defaults: { _controller: GistSalesReportBundle:MainSalesReport:gridReport,id: null,department: null, date_from: null, date_to: null, position: null, rank: null, gender: null, days: null, late: null, late_to: null, undertime: null, undertime_to: null, status: null, location: null }

gist_sales_report_main_ajax:
    path:    /attendance/{id}/{date_from}/{date_to}/{position}/{rank}/{gender}/{days}/{late}/{late_to}/{undertime}/{undertime_to}/{status}/{location}
    defaults: { _controller: GistSalesReportBundle:MainSalesReport:gridReport,id: null,department: null, date_from: null, date_to: null, position: null, rank: null, gender: null, days: null, late: null, late_to: null, undertime: null, undertime_to: null, status: null, location: null }

gist_sales_report_sales_order_summary:
    path: /sales-orders
    defaults: { _controller: GistSalesReportBundle:SalesOrderReport:index }


gist_sales_report_sales_entries_summary:
    path: /sales-entries
    defaults: { _controller: GistSalesReportBundle:SalesEntriesReport:index }


gist_sales_report_sales_per_day_summary:
    path: /sales-daily
    defaults: { _controller: GistSalesReportBundle:SalesPerDayReport:index }


gist_sales_report_sales_by_consultant_summary:
    path: /sales-consultant
    defaults: { _controller: GistSalesReportBundle:SalesByConsultantReport:index }

gist_sales_report_sales_by_pos_summary:
    path: /sales-pos
    defaults: { _controller: GistSalesReportBundle:SalesByPOSReport:index }

gist_sales_report_sales_by_location_summary:
    path: /sales-location
    defaults: { _controller: GistSalesReportBundle:SalesByLocationReport:index }

gist_sales_report_sales_by_product_summary:
    path: /sales-product
    defaults: { _controller: GistSalesReportBundle:SalesByProductReport:index }

gist_sales_report_sales_commission_summary:
    path: /sales-commission
    defaults: { _controller: GistSalesReportBundle:SalesCommissionReport:index }