
gist_inv_counting_gridform_index:
    pattern: /list
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:CountingForm:index }

gist_inv_counting_gridform_grid:
    pattern: /grid
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:CountingForm:grid }


gist_inv_counting_gridform_grid_search:
    pattern: /grid/{pos_loc_id}/{inv_type}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:CountingForm:gridSearch }

gist_inv_counting_gridform_get_prod_details:
    path:     /grid/get_prod_info/{id}/{inv_id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:CountingForm:getProductDetailsStock }

gist_inv_counting_gridform_save_stock_threshold:
    path:     /grid/save_stock_threshold/{id}/{min}/{max}/{pos_loc_id}/{inv_id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:CountingForm:saveStockThreshold }


gist_inv_counting_gridform_pos_grid_data:
    pattern: /pos/grid/{pos_loc_id}/{inv_type}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:CountingForm:getCountingFormData }