gist_inv_counting_index:
    pattern: /list
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:Counting:index }

gist_inv_counting_add_form:
    pattern: /add
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:Counting:addForm }

gist_inv_counting_add_submit:
    pattern: /add
    methods: [POST]
    defaults: { _controller: GistInventoryBundle:Counting:addSubmit }

gist_inv_counting_edit_form:
    pattern: /edit/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:Counting:editForm }
    
gist_inv_counting_edit_submit:
    pattern: /edit/{id}
    methods: [POST]
    defaults: { _controller: GistInventoryBundle:Counting:editSubmit }

gist_inv_counting_delete:
    pattern: /delete/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:Counting:delete }

gist_inv_counting_grid:
    pattern: /grid
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:Counting:grid }

gist_inv_counting_ajax_get:
    pattern: /ajax/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:Counting:ajaxGet }

gist_inv_counting_print:
    pattern: /print/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:Counting:printPDF }    