gist_inv_damaged_items_index:
    pattern: /list
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:index }

gist_inv_damaged_items_add_entries_form:
    pattern: /add_entries
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:addFormEntries }

gist_inv_damaged_items_add_entries_submit:
    pattern: /add_entries
    methods: [POST]
    defaults: { _controller: GistInventoryBundle:DamagedItems:addSubmitEntries }

#gist_inv_damaged_items_view_inventory_entries:
#    pattern: /view_entries/{id}
#    methods: [GET]
#    defaults: { _controller: GistInventoryBundle:DamagedItems:viewEntries }

gist_inv_damaged_items_add_return_form:
    pattern: /add_return/{ids}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:addFormReturn }

gist_inv_damaged_items_add_return_submit:
    pattern: /add_return/{ids}
    methods: [POST]
    defaults: { _controller: GistInventoryBundle:DamagedItems:addReturnSubmit }

gist_inv_damaged_items_receive_return_form:
    pattern: /receive/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:viewFormReceive }

gist_inv_damaged_items_submit_return_form:
    pattern: /receive/{id}
    methods: [POST]
    defaults: { _controller: GistInventoryBundle:DamagedItems:submitFormReceive }

gist_inv_damaged_items_edit_form:
    pattern: /edit/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:editForm }

gist_inv_damaged_items_edit_submit:
    pattern: /edit/{id}
    methods: [POST]
    defaults: { _controller: GistInventoryBundle:DamagedItems:editSubmit }

gist_inv_damaged_items_delete:
    pattern: /delete/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:delete }

gist_inv_damaged_items_grid:
    pattern: /grid
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:grid }

gist_inv_damaged_items_ajax_get:
    pattern: /ajax/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:ajaxGet }

gist_inv_damaged_items_print:
    pattern: /print/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:printPDF }

#--------------------------------------------------------------------------------------------------------
#FOR POS
#--------------------------------------------------------------------------------------------------------
#FOR GRID
gist_inv_damaged_items_get_from_pos:
    path:     /get/from/{pos_loc_id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:getSentFromPOS }

gist_inv_damaged_items_get_to_pos:
    path:     /get/to/{pos_loc_id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:getSentToPOS }

gist_inv_damaged_items_pos_dmg_stocks:
    path:     /get/damaged_stocks/{pos_loc_id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:getDMGStockListPOS }
#END FOR GRID

#LOCATION OPTIONS
gist_inv_damaged_items_get_location_options:
    path:     /get/loc_options/{pos_loc_id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:getLocationOptions }

#POS GET SELECTED ITEMS
gist_inv_damaged_items_pos_get_selected_products:
    path:     /pos/get_selected_for_return/{ids}/{iacc}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:getSelectedEntries }

#POS SAVE NEW DAMAGE ITEM/S ENTRY
gist_inv_damaged_items_pos_add_entries:
    path:     /pos/add_entries2/{loc_id}/{uid}/{entries}/{posx}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:posAddDamagedEntries }

#POS SAVE NEW DAMAGE ITEM OBJECT/ FOR RETURN
gist_inv_damaged_items_pos_add_return:
    path:     /pos/save_for_return/{description}/{user}/{source}/{destination}/{entries}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:posAddReturn }

#POS GET RECV FORM DATA
gist_inv_damaged_items_pos_get_recv_form_data:
    path:     /pos/get_receive_form_data/{id}/{pos_loc_id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:getPOSFormData }

#POS GET RECV FORM DATA ENTRIES
gist_inv_damaged_items_pos_get_recv_form_data_entries:
    path:     /pos/get_receive_form_data_entries/{id}/{pos_loc_id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:getPOSFormDataEntries }

#POS GET RECV FORM DATA ENTRIES
gist_inv_damaged_items_pos_receive_items:
    path:     /pos/receive_items/{pos_loc_id}/{uid}/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:posReceiveItems }

#POS GET DAMAGED STOCK SUMM
gist_inv_damaged_items_pos_stock_summ:
    path:    /pos/summary_table/{pos_loc_id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:getPOSDamageStock }

#----------------------------OLD-------------------------------------
gist_inv_damaged_items_get_data_entries:
    path:     /get/data_entries/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:getPOSFormDataEntries }

gist_inv_damaged_items_update_status:
    path:     /update_status/{id}/{userId}/{status}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:updatePOSDamagedItems }

gist_inv_damaged_items_add_new:
    path:     /add_new/{src}/{user}/{description}/{entries}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:addPOSDamagedItems }

gist_inv_damaged_items_summary_ajax_grid:
    path:    /summary_table/ajax
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:gridSearchSummary }

gist_inv_damaged_items_summary_ajax_grid_to_send:
    path:    /summary_table_to_send/ajax
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:gridSearchToSend }

gist_inv_damaged_items_summary_ajax_grid_to_receive:
    path:    /summary_table_to_receive/ajax
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:gridSearchToReceive }

gist_inv_damaged_items_ajax_grid:
    path:    /search_product/ajax
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:gridSearchProduct }

gist_inv_damaged_items_search_ajax_grid:
    path:    /search_product/ajax2/{category}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:gridSearchProduct, category: null }

gist_inv_damaged_items_get_prod_cat_options:
    path:     /get/prod_cats
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:getProductCategoryOptions }

gist_inv_damaged_items_get_data:
    path:     /get/data/{id}/{pos_loc_id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:getPOSFormData }

gist_inv_damaged_items_get_reason_options:
    path:     /get/reasons
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:DamagedItems:getReasonOptions }