
gist_inv_existing_stock_index:
    pattern: /list/{tab}/{pos_loc_id}/{inv_type}/{date_from}/{date_to}/{prod_pos_loc_id}/{prod_inv_type}/{prod_date_from}/{prod_date_to}/{product_name}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:ExistingStock:index, tab: null, pos_loc_id: null, inv_type: null, date_from: null, date_to: null, prod_pos_loc_id: null, prod_inv_type: null, prod_date_from: null, prod_date_to: null, product_name: null }

gist_inv_existing_stock_grid:
    pattern: /grid
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:ExistingStock:grid }


gist_inv_existing_stock_grid_search:
    pattern: /grid/{pos_loc_id}/{inv_type}/{date_from}/{date_to}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:ExistingStock:gridSearch }

gist_inv_existing_stock_get_prod_details:
    path:     /grid/get_prod_info/{id}/{inv_id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:ExistingStock:getProductDetailsStock }

gist_inv_existing_stock_save_stock_threshold:
    path:     /grid/save_stock_threshold/{id}/{min}/{max}/{pos_loc_id}/{inv_id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:ExistingStock:saveStockThreshold }


gist_inv_existing_stock_pos_grid_data:
    pattern: /pos/grid/{origin}/{pos_loc_id}/{inv_type}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:ExistingStock:getExistingStockData }

gist_inv_existing_stock_pos_other_visibility:
    pattern: /pos/visibility/{pos_loc_id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:ExistingStock:getPOSVisibility }