gist_inv_pos_index:
    path:     /pos_app
    methods:  [GET]
    defaults: { _controller: GistInventoryBundle:POS:index }

gist_inv_pos_add_form:
    path:     /pos1
    methods:  [GET]
    defaults: { _controller: GistInventoryBundle:POS:addForm }

gist_inv_pos_add_form_submit:
    path:     /pos1
    methods:  [POST]
    defaults: { _controller: GistInventoryBundle:POS:addSubmit }

gist_inv_pos_grid:
    path:     /pos1/grid
    methods:  [GET]
    defaults: { _controller: GistInventoryBundle:POS:grid }

gist_inv_pos_edit_form:
    path:     /pos1/{id}
    methods:  [GET]
    defaults: { _controller: GistInventoryBundle:POS:editForm }

gist_inv_pos_edit_submit:
    pattern: /pos1/{id}
    methods: [POST]
    defaults: { _controller: GistInventoryBundle:POS:editSubmit }

gist_inv_pos_delete:
    pattern: /pos1/delete/{id}
    defaults: { _controller: GistInventoryBundle:POS:delete }


gist_inv_pos_get_categories:
    pattern: /get/product_categories
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:POS:getProductCategories }

gist_inv_pos_get_products:
    pattern: /get/products/{category_id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:POS:getProducts }

gist_inv_pos_get_vat:
    pattern: /get/vat
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:POS:getVAT }

gist_inv_pos_get_banks:
    pattern: /get/banks
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:POS:getBanks }