gist_inv_stock_transfer_index:
    pattern: /list
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:StockTransfer:index }

gist_inv_stock_transfer_add_form:
    pattern: /add
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:StockTransfer:addForm }

gist_inv_stock_transfer_add_submit:
    pattern: /add
    methods: [POST]
    defaults: { _controller: GistInventoryBundle:StockTransfer:addSubmit }

gist_inv_stock_transfer_edit_form:
    pattern: /edit/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:StockTransfer:editForm }

gist_inv_stock_transfer_edit_submit:
    pattern: /edit/{id}
    methods: [POST]
    defaults: { _controller: GistInventoryBundle:StockTransfer:editSubmit }

gist_inv_stock_transfer_delete:
    pattern: /delete/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:StockTransfer:delete }

gist_inv_stock_transfer_grid:
    pattern: /grid
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:StockTransfer:grid }

gist_inv_stock_transfer_ajax_get:
    pattern: /ajax/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:StockTransfer:ajaxGet }

gist_inv_stock_transfer_print:
    pattern: /print/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:StockTransfer:printPDF }

#    FOR POS
gist_inv_stock_transfer_get_from_pos:
    path:     /get/from/{pos_loc_id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:StockTransfer:getSentFromPOS }

gist_inv_stock_transfer_get_to_pos:
    path:     /get/to/{pos_loc_id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:StockTransfer:getSentToPOS }

gist_inv_stock_transfer_get_location_options:
    path:     /get/loc_options/{pos_loc_id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:StockTransfer:getLocationOptions }

gist_inv_stock_transfer_get_data:
    path:     /get/data/{id}/{pos_loc_id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:StockTransfer:getPOSFormData }

gist_inv_stock_transfer_get_data_entries:
    path:     /get/data_entries/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:StockTransfer:getPOSFormDataEntries }

gist_inv_stock_transfer_update_status:
    path:     /update_status/{id}/{userId}/{status}/{entries}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:StockTransfer:updatePOSStockTransfer }

gist_inv_stock_transfer_add_new:
    path:     /add_new/{src}/{dest}/{user}/{description}/{entries}/{status}/{id}
    methods: [GET]
    defaults: { _controller: GistInventoryBundle:StockTransfer:addPOSStockTransfer }