parameters:
#    hris_workforce_management.example.class: Hris\WorkforceBundle\Example

services:
    attendance_report_manager:
        class: Hris\ReportBundle\Model\AttendanceReportManager
        arguments: [ "@doctrine.orm.entity_manager" ]