menu_items:
    - id: cat_config
      acl: cat_config.menu
      label: General Settings
      icon: fa-wrench
    - id: cat_config_index
      acl: cat_config.menu
      label: Settings
      parent: cat_config
    - id: hris_com_info_index
      acl: hris_com_info.menu
      label: Company Information
      parent: cat_config