acl:
    # HR Settings Menu
    - category: HRIS Settings
      entries:
      - id: hris_admin.menu
        label: "Menu"

    # Basic Settings
    - category: Basic Settings
      entries:
      - id: hris_admin_basic_settings.menu
        label: "Menu"
      - id: hris_admin_basic_settings.view
        label: "View"
      - id: hris_admin_basic_settings.add
        label: "Add"
      - id: hris_admin_basic_settings.edit
        label: "Edit"

    # Basic Settings
    - category: Overtime Matrix
      entries:
      - id: hris_admin_overtime_matrix.menu
        label: "Menu"
      - id: hris_admin_overtime_matrix.view
        label: "View"
      - id: hris_admin_overtime_matrix.add
        label: "Add"
      - id: hris_admin_overtime_matrix.edit
        label: "Edit"
      - id: hris_admin_overtime_matrix.delete
        label: "Delete"

    # Basic Settings
    - category: Night Differential Matrix
      entries:
      - id: hris_admin_night_differential_matrix.menu
        label: "Menu"
      - id: hris_admin_night_differential_matrix.view
        label: "View"
      - id: hris_admin_night_differential_matrix.add
        label: "Add"
      - id: hris_admin_night_differential_matrix.edit
        label: "Edit"
      - id: hris_admin_night_differential_matrix.delete
        label: "Delete"

    # Events Sub-menu
    - category: Events
      entries:
      - id: hris_admin_events.menu
        label: "Menu"
      - id: hris_admin_events.view
        label: "View"
      - id: hris_admin_events.add
        label: "Add"
      - id: hris_admin_events.edit
        label: "Edit"
      - id: hris_admin_events.delete
        label: "Delete"

    # Benefit Sub-menu
    - category: Benefit
      entries:
      - id: hris_admin_benefit.menu
        label: "Menu"
      - id: hris_admin_benefit.view
        label: "View"
      - id: hris_admin_benefit.add
        label: "Add"
      - id: hris_admin_benefit.edit
        label: "Edit"
      - id: hris_admin_benefit.delete
        label: "Delete"

    # Leave Type
    - category: Leave Type
      entries:
      - id: hris_admin_leave_type.menu
        label: "Menu"
      - id: hris_admin_leave_type.view
        label: "View"
      - id: hris_admin_leave_type.add
        label: "Add"
      - id: hris_admin_leave_type.edit
        label: "Edit"
      - id: hris_admin_leave_type.delete
        label: "Delete"

    # Overtime
    - category: Overtime
      entries:
      - id: hris_admin_otsetting.menu
        label: "Menu"
      - id: hris_admin_otsetting.edit
        label: "Edit"

    # Tax Matrix
    - category: Tax Matrix
      entries:
        - id: hris_admin_tax_matrix.menu
          label: "Menu"
        - id: hris_admin_tax_matrix.view
          label: "View"
        - id: hris_admin_tax_matrix.add
          label: "Add"
        - id: hris_admin_tax_matrix.edit
          label: "Edit"
        - id: hris_admin_tax_matrix.delete
          label: "Delete"

    # Bonus
    - category: Bonus
      entries:
        - id: hris_payroll_settings_bonus.menu
          label: "Menu"
        - id: hris_payroll_settings_bonus.view
          label: "View"
        - id: hris_payroll_settings_bonus.add
          label: "Add"
        - id: hris_payroll_settings_bonus.edit
          label: "Edit"
        - id: hris_payroll_settings_bonus.delete
          label: "Delete"

    # Fines
    - category: Fines
      entries:
        - id: hris_payroll_settings_fines.menu
          label: "Menu"
        - id: hris_payroll_settings_fines.view
          label: "View"
        - id: hris_payroll_settings_fines.add
          label: "Add"
        - id: hris_payroll_settings_fines.edit
          label: "Edit"
        - id: hris_payroll_settings_fines.delete
          label: "Delete"

    # Deposit
    - category: Deposit
      entries:
        - id: hris_payroll_settings_deposit.menu
          label: "Menu"
        - id: hris_payroll_settings_deposit.view
          label: "View"
        - id: hris_payroll_settings_deposit.add
          label: "Add"
        - id: hris_payroll_settings_deposit.edit
          label: "Edit"
        - id: hris_payroll_settings_deposit.delete
          label: "Delete"

    # Incentive
    - category: Incentive
      entries:
        - id: hris_payroll_settings_incentive.menu
          label: "Menu"
        - id: hris_payroll_settings_incentive.view
          label: "View"
        - id: hris_payroll_settings_incentive.add
          label: "Add"
        - id: hris_payroll_settings_incentive.edit
          label: "Edit"
        - id: hris_payroll_settings_incentive.delete
          label: "Delete"

    # Biometrics
#    - category: Biometrics Settings
#      entries:
#       - id: hris_biometrics.menu
#         label: "Menu"
#       - id: hris_biometrics.view
#         label: "View"
#       - id: hris_biometrics.add
#         label: "Add"

    # Form Codes Sub-menu
#    - category: HR Form Codes
#      entries:
#      - id: hris_admin_form_codes.menu
#        label: "Menu"
#      - id: hris_admin_form_codes.view
#        label: "View"
#      - id: hris_admin_form_codes.edit
#        label: "Edit"

    # Leave Rules
#    - category: Leave Rules
#      entries:
#      - id: hris_admin_leave_rules.menu
#        label: "Menu"
#      - id: hris_admin_leave_rules.view
#        label: "View"
#      - id: hris_admin_leave_rules.add
#        label: "Add"
#      - id: hris_admin_leave_rules.edit
#        label: "Edit"
#      - id: hris_admin_leave_rules.delete
#        label: "Delete"

    # Appraisal Settings
#    - category: Appraisal Settings
#      entries:
#      - id: hris_admin_appraisal_settings.menu
#        label: "Menu"
#      - id: hris_admin_appraisal_settings.view
#        label: "View"
#      - id: hris_admin_appraisal_settings.add
#        label: "Add"
#      - id: hris_admin_appraisal_settings.edit
#        label: "Edit"
#      - id: hris_admin_appraisal_settings.delete
#        label: "Delete"


    # Time Schedule Sub-menu
#    - category: Employee Time Schedule
#      entries:
#        - id: hris_admin_schedules.menu
#          label: "Menu"
#        - id: hris_admin_schedules.menu
#          label: "Menu"
#        - id: hris_admin_schedules.view
#          label: "View"
#        - id: hris_admin_schedules.add
#          label: "Add"
#        - id: hris_admin_schedules.edit
#          label: "Edit"
#        - id: hris_admin_schedules. delete
#          label: "Delete"
#
#    # Checkist Sub-menu
#    - category: Employment Checklist
#      entries:
#      - id: hris_admin_checklist.menu
#        label: "Menu"
#      - id: hris_admin_checklist.view
#        label: "View"
#      - id: hris_admin_checklist.add
#        label: "Add"
#      - id: hris_admin_checklist.edit
#        label: "Edit"
#      - id: hris_admin_checklist.delete
#        label: "Delete"
#
#    # Holiday Sub-menu
#    - category: Holiday
#      entries:
#      - id: hris_admin_holiday.menu
#        label: "Menu"
#      - id: hris_admin_holiday.view
#        label: "View"
#      - id: hris_admin_holiday.add
#        label: "Add"
#      - id: hris_admin_holiday.edit
#        label: "Edit"
#      - id: hris_admin_holiday.delete
#        label: "Delete"
#
#    # Downloadables Sub-menu
#    - category: Downloadables
#      entries:
#      - id: hris_admin_downloadables.menu
#        label: "Menu"
#      - id: hris_admin_downloadables.view
#        label: "View"
#      - id: hris_admin_downloadables.add
#        label: "Add"
#      - id: hris_admin_downloadables.edit
#        label: "Edit"
#      - id: hris_admin_downloadables.delete
#        label: "Delete"

    # Leave Settings
#    - category: Leave Settings
#      entries:
#      - id: hris_admin_leave.menu
#        label: "Menu"

#    # Position / Job Title Sub-menu
#    - category: Position
#      entries:
#      - id: hris_admin_jobtitles.menu
#        label: "Menu"
#      - id: hris_admin_jobtitles.view
#        label: "View"
#      - id: hris_admin_jobtitles.add
#        label: "Add"
#      - id: hris_admin_jobtitles.edit
#        label: "Edit"
#      - id: hris_admin_jobtitles.delete
#        label: "Delete"
#
#    # Job Level
#    - category: Job Level
#      entries:
#      - id: hris_admin_joblevel.menu
#        label: "Menu"
#      - id: hris_admin_joblevel.view
#        label: "View"
#      - id: hris_admin_joblevel.add
#        label: "Add"
#      - id: hris_admin_joblevel.edit
#        label: "Edit"
#      - id: hris_admin_joblevel.delete
#        label: "Delete"

    # Location Sub-menu
#    - category: Location
#      entries:
#      - id: hris_admin_location.menu
#        label: "Menu"
#      - id: hris_admin_location.view
#        label: "View"
#      - id: hris_admin_location.add
#        label: "Add"
#      - id: hris_admin_location.edit
#        label: "Edit"
#      - id: hris_admin_location.delete
#        label: "Delete"

    # Department Sub-menu
#    - category: Department
#      entries:
#      - id: hris_admin_department.menu
#        label: "Menu"
#      - id: hris_admin_department.view
#        label: "View"
#      - id: hris_admin_department.add
#        label: "Add"
#      - id: hris_admin_department.edit
#        label: "Edit"
#      - id: hris_admin_department.delete
#        label: "Delete"

    # Admin Menu
#    - category: Administration
#      entries:
#      - id: cat_admin.menu
#        label: "Menu"

    # Omnibar
#    - category: Omnibar
#      entries:
#      - id: hris_omnibar.view
#        label: "View"
