parameters:
#    catalyst_flot.example.class: Catalyst\FlotBundle\Example

services:
#    catalyst_flot.example:
#        class: %catalyst_flot.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
