menu_items:
    - id: cat_hris_menu
      acl: cat_hris.menu
      label: User
      icon: fa-user
    - id: cat_user_user_index
      acl: cat_user_user.menu
      label: User
      parent: cat_hris_menu
    - id: cat_user_group_index
      acl: cat_user_group.menu
      label: Position
      parent: cat_hris_menu
    - id: cat_user_department_index
      acl: cat_user_department.menu
      label: Department
      parent: cat_hris_menu
    - id: cat_user_items_list_index
      acl: cat_user_items_list.menu
      label: Items List
      parent: cat_hris_menu

    - id: gist_loc_menu
      acl: gist_loc.menu
      label: Location
      parent: cat_hris_menu
    - id: gist_loc_areas_index
      acl: gist_loc_areas.menu
      label: Areas
      parent: gist_loc_menu
    - id: gist_loc_regions_index
      acl: gist_loc_regions.menu
      label: Regions
      parent: gist_loc_menu
    - id: gist_loc_pos_locations_index
      acl: gist_loc_pos_locations.menu
      label: POS Locations
      parent: gist_loc_menu