cat_user_user_index:
    pattern: /users
    methods: [GET]
    defaults: { _controller: GistUserBundle:User:index }

cat_user_user_add_form:
    pattern: /user
    methods: [GET]
    defaults: { _controller: GistUserBundle:User:addForm }

cat_user_user_add_submit:
    pattern: /user
    methods: [POST]
    defaults: { _controller: GistUserBundle:User:addSubmit }

cat_user_user_edit_form:
    pattern: /user/{id}
    methods: [GET]
    defaults: { _controller: GistUserBundle:User:editForm }

cat_user_user_edit_submit:
    pattern: /user/{id}
    methods: [POST]
    defaults: { _controller: GistUserBundle:User:editSubmit }

cat_user_user_delete:
    pattern: /user/{id}/delete
    methods: [GET]
    defaults: { _controller: GistUserBundle:User:delete }

cat_user_user_grid:
    pattern: /users/grid
    methods: [GET]
    defaults: { _controller: GistUserBundle:User:grid }


#DEPARTMENT
cat_user_department_index:
    pattern: /departments
    methods: [GET]
    defaults: { _controller: GistUserBundle:Department:index }

cat_user_department_add_form:
    pattern: /department
    methods: [GET]
    defaults: { _controller: GistUserBundle:Department:addForm }

cat_user_department_add_submit:
    pattern: /department
    methods: [POST]
    defaults: { _controller: GistUserBundle:Department:addSubmit }

cat_user_department_edit_form:
    pattern: /department/{id}
    methods: [GET]
    defaults: { _controller: GistUserBundle:Department:editForm }

cat_user_department_edit_submit:
    pattern: /department/{id}
    methods: [POST]
    defaults: { _controller: GistUserBundle:Department:editSubmit }

cat_user_department_delete:
    pattern: /department/{id}/delete
    methods: [GET]
    defaults: { _controller: GistUserBundle:Department:delete }

cat_user_department_grid:
    pattern: /departments/grid
    methods: [GET]
    defaults: { _controller: GistUserBundle:Department:grid }

#POSITION


cat_user_group_index:
    pattern: /groups
    methods: [GET]
    defaults: { _controller: GistUserBundle:Group:index }

cat_user_group_add_form:
    pattern: /group
    methods: [GET]
    defaults: { _controller: GistUserBundle:Group:addForm }

cat_user_group_add_submit:
    pattern: /group
    methods: [POST]
    defaults: { _controller: GistUserBundle:Group:addSubmit }

cat_user_group_edit_form:
    pattern: /group/{id}
    methods: [GET]
    defaults: { _controller: GistUserBundle:Group:editForm }

cat_user_group_edit_submit:
    pattern: /group/{id}
    methods: [POST]
    defaults: { _controller: GistUserBundle:Group:editSubmit }

cat_user_group_delete:
    pattern: /group/{id}/delete
    methods: [GET]
    defaults: { _controller: GistUserBundle:Group:delete }

cat_user_group_get_positions:
    pattern: /group/get_positions/{parent}
    methods: [GET]
    defaults: { _controller: GistUserBundle:Group:getPositions }

cat_user_group_acl_editor:
    pattern: /group/acl_editor/{group_id}
    methods: [GET]
    defaults: { _controller: GistUserBundle:Group:aclEditor }

cat_user_group_acl_editor_submit:
    pattern: /group/acl_editor/{group_id}
    methods: [POST]
    defaults: { _controller: GistUserBundle:Group:aclUpdate }



rm_file:
    pattern: /user/removeFile/{file}/{uid}
    methods: [GET]
    defaults: { _controller: GistUserBundle:User:deleteFile, file: null }
    requirements:
        file:    '[a-zA-Z0-9-_\/-\s.^]+'


#ITEMS LIST
cat_user_items_list_index:
    pattern: /itemslist
    methods: [GET]
    defaults: { _controller: GistUserBundle:ItemsList:index }

cat_user_items_list_add_form:
    pattern: /item
    methods: [GET]
    defaults: { _controller: GistUserBundle:ItemsList:addForm }

cat_user_items_list_add_submit:
    pattern: /item
    methods: [POST]
    defaults: { _controller: GistUserBundle:ItemsList:addSubmit }

cat_user_items_list_edit_form:
    pattern: /item/{id}
    methods: [GET]
    defaults: { _controller: GistUserBundle:ItemsList:editForm }

cat_user_items_list_edit_submit:
    pattern: /item/{id}
    methods: [POST]
    defaults: { _controller: GistUserBundle:ItemsList:editSubmit }

cat_user_items_list_delete:
    pattern: /item/{id}/delete
    methods: [GET]
    defaults: { _controller: GistUserBundle:ItemsList:delete }

cat_user_items_list_grid:
    pattern: /itemslist/grid
    methods: [GET]
    defaults: { _controller: GistUserBundle:ItemsList:grid }

#AREA
gist_loc_areas_index:
    pattern: /areas
    methods: [GET]
    defaults: { _controller: GistUserBundle:Areas:index }

gist_loc_areas_add_form:
    pattern: /area
    methods: [GET]
    defaults: { _controller: GistUserBundle:Areas:addForm }

gist_loc_areas_add_submit:
    pattern: /area
    methods: [POST]
    defaults: { _controller: GistUserBundle:Areas:addSubmit }

gist_loc_areas_edit_form:
    pattern: /area/{id}
    methods: [GET]
    defaults: { _controller: GistUserBundle:Areas:editForm }

gist_loc_areas_edit_submit:
    pattern: /area/{id}
    methods: [POST]
    defaults: { _controller: GistUserBundle:Areas:editSubmit }

gist_loc_areas_delete:
    pattern: /area/{id}/delete
    methods: [GET]
    defaults: { _controller: GistUserBundle:Areas:delete }

gist_loc_areas_grid:
    pattern: /areas/grid
    methods: [GET]
    defaults: { _controller: GistUserBundle:Areas:grid }


gist_loc_areas_group_view:
    pattern: /area/group/{id}
    methods: [GET]
    defaults: { _controller: GistUserBundle:Areas:viewGroup }

#POS LOCS
gist_loc_pos_locations_index:
    pattern: /pos_locations
    methods: [GET]
    defaults: { _controller: GistUserBundle:POSLocations:index }

gist_loc_pos_locations_add_form:
    pattern: /pos_location
    methods: [GET]
    defaults: { _controller: GistUserBundle:POSLocations:addForm }

gist_loc_pos_locations_add_submit:
    pattern: /pos_location
    methods: [POST]
    defaults: { _controller: GistUserBundle:POSLocations:addSubmit }

gist_loc_pos_locations_edit_form:
    pattern: /pos_location/{id}
    methods: [GET]
    defaults: { _controller: GistUserBundle:POSLocations:editForm }

gist_loc_pos_locations_edit_submit:
    pattern: /pos_location/{id}
    methods: [POST]
    defaults: { _controller: GistUserBundle:POSLocations:editSubmit }

gist_loc_pos_locations_delete:
    pattern: /pos_location/{id}/delete
    methods: [GET]
    defaults: { _controller: GistUserBundle:POSLocations:delete }

gist_loc_pos_locations_grid:
    pattern: /pos_locations/grid
    methods: [GET]
    defaults: { _controller: GistUserBundle:POSLocations:grid }