cat_user_user_index:
    pattern: /users
    methods: [GET]
    defaults: { _controller: GistUserBundle:User:index }

cat_user_user_add_form:
    pattern: /user
    methods: [GET]
    defaults: { _controller: GistUserBundle:User:addForm }

cat_user_user_add_submit:
    pattern: /user
    methods: [POST]
    defaults: { _controller: GistUserBundle:User:addSubmit }

cat_user_user_edit_form:
    pattern: /user/{id}
    methods: [GET]
    defaults: { _controller: GistUserBundle:User:editForm }

cat_user_user_edit_submit:
    pattern: /user/{id}
    methods: [POST]
    defaults: { _controller: GistUserBundle:User:editSubmit }

cat_user_user_delete:
    pattern: /user/{id}/delete
    methods: [GET]
    defaults: { _controller: GistUserBundle:User:delete }

cat_user_user_grid:
    pattern: /users/grid
    methods: [GET]
    defaults: { _controller: GistUserBundle:User:grid }


#POSITION
cat_user_position_index:
    pattern: /position
    methods: [GET]
    defaults: { _controller: GistUserBundle:Position:index }

cat_user_position_add_form:
    pattern: /position
    methods: [GET]
    defaults: { _controller: GistUserBundle:Position:addForm }

cat_user_position_add_submit:
    pattern: /position
    methods: [POST]
    defaults: { _controller: GistUserBundle:Position:addSubmit }

cat_user_position_edit_form:
    pattern: /position/{id}
    methods: [GET]
    defaults: { _controller: GistUserBundle:Position:editForm }

cat_user_position_edit_submit:
    pattern: /position/{id}
    methods: [POST]
    defaults: { _controller: GistUserBundle:Position:editSubmit }

cat_user_position_delete:
    pattern: /position/{id}/delete
    methods: [GET]
    defaults: { _controller: GistUserBundle:Position:delete }

cat_user_position_grid:
    pattern: /position/grid
    methods: [GET]
    defaults: { _controller: GistUserBundle:Position:grid }

#DEPARTMENT


cat_user_group_index:
    pattern: /groups
    methods: [GET]
    defaults: { _controller: GistUserBundle:Group:index }

cat_user_group_add_form:
    pattern: /group
    methods: [GET]
    defaults: { _controller: GistUserBundle:Group:addForm }

cat_user_group_add_submit:
    pattern: /group
    methods: [POST]
    defaults: { _controller: GistUserBundle:Group:addSubmit }

cat_user_group_edit_form:
    pattern: /group/{id}
    methods: [GET]
    defaults: { _controller: GistUserBundle:Group:editForm }

cat_user_group_edit_submit:
    pattern: /group/{id}
    methods: [POST]
    defaults: { _controller: GistUserBundle:Group:editSubmit }

cat_user_group_delete:
    pattern: /group/{id}/delete
    methods: [GET]
    defaults: { _controller: GistUserBundle:Group:delete }
