## Departments

cat_notification_get:
    path:  /all
    methods: [GET]
    defaults: { _controller: CatalystNotificationBundle:Notification:notifications }

cat_notification_read:
    path:  /read/{id}
    methods: [GET]
    defaults: { _controller: CatalystNotificationBundle:Notification:setRead }

cat_notification_index:
    path:  /
    methods: [GET]
    defaults: { _controller: CatalystNotificationBundle:Notification:index }